In [9]:
import numpy as np

In [10]:
# Membuat matriks
A = np.array([[80, 30, 25], [50, 20, 10]])
B = np.array([[30, 60, 15], [10, 30, 30]])
C = A + B
print(C)

[[110  90  40]
 [ 60  50  40]]


In [11]:
# Melakukan operasi dot product
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
C = np.dot(A, B)
print(C)

2025


In [12]:
# Melakukan operasi cross product
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])
C = np.cross(A, B)
print(C)

[-305 -110  350]
